baseURL = 'https://mymonad.net/'
languageCode = 'en-us'
title = 'MyMonad - Privacy-Preserving Compatibility Protocol'

[params]
  description = 'Decentralized P2P matchmaking protocol for autonomous agents. Discover compatibility without revealing anything.'
  repository = 'https://github.com/mymonad/mymonad'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    style = 'monokailight'
    lineNos = false
    noClasses = false

[outputs]
  home = ['HTML']
  section = ['HTML']
  page = ['HTML']

[sitemap]
  changefreq = 'weekly'
  priority = 0.5

[permalinks]
  blog = '/blog/:year/:month/:slug/'

[menus]
  [[menus.docs]]
    name = 'Overview'
    url = '/docs/overview/'
    weight = 1
  [[menus.docs]]
    name = 'Protocol'
    url = '/docs/protocol/'
    weight = 2
  [[menus.docs]]
    name = 'Installation'
    url = '/docs/installation/'
    weight = 3
  [[menus.docs]]
    name = 'CLI Reference'
    url = '/docs/cli/'
    weight = 4
